import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process,LLM
from dotenv import load_dotenv
from tools.google_news_tool import GoogleNewsRSS
from tools.email_sender import EmailSendingTool 

# Load environment variables from .env file
load_dotenv() 

# 1. Initialize LLM and Tools
# The GOOGLE_API_KEY is read automatically by ChatGoogleGenerativeAI
gemini_llm = LLM(
    model="gemini/gemini-2.5-flash",
    temperature=0.3 
)

# SerperDevTool needs SERPER_API_KEY in .env
news_fetcher_tool = GoogleNewsRSS()
email_sender_tool = EmailSendingTool() # Your custom email tool

# 2. Define Agents
researcher = Agent(
    role='Senior Tech & Job Market Analyst',
    goal='Find the top 5 most significant news articles on AI trends, new tech, and the job market.',
    backstory='An expert analyst who structures complex data into clear, concise summaries.',
    tools=[news_fetcher_tool],
    llm=gemini_llm,
    verbose=True,
    allow_delegation=False
)

strategist = Agent(
    role='AI News Summary Writer',
    goal='Synthesize research into a polished, engaging, and ready-to-post LinkedIn update.',
    backstory='A creative content strategist who formats technical information for maximum social media engagement.',
    llm=gemini_llm,
    verbose=True,
    allow_delegation=False
)

deliverer = Agent(
    role='System Integrator',
    goal='Securely send the final LinkedIn post draft to the user’s email for posting.',
    backstory='A reliable automation expert who manages the final delivery and notification process.',
    tools=[email_sender_tool],
    llm=gemini_llm,
    verbose=True,
    allow_delegation=False
)

# 3. Define Tasks
research_task = Task(
    description=(
        "Search for the top 5 recent (last 48 hours) articles covering major AI breakthroughs, "
        "AI job market trends, and new AI tools. Extract the headline, a one-sentence summary, "
        "and the source URL for each. Output this structured data."
    ),
    expected_output='A JSON list containing 5 structured news items (headline, summary, URL).',
    agent=researcher
)

summarize_task = Task(
    description=(
        "Review the structured news items (context) and write a single, professional LinkedIn post "
        "(max 500 words). The post MUST include a catchy hook, 3-5 clear bullet points based on the "
        "findings, a thought-provoking closing question, and a list of 5 relevant hashtags "
        "(e.g., #AI, #FutureOfWork, #GeminiAPI)."
    ),
    expected_output='The final, fully formatted LinkedIn post text as a single string.',
    context=[research_task], # The output of the previous task is the context for this one
    agent=strategist
)

email_task = Task(
    description=(
        "Use the 'EmailSender' tool to send the final LinkedIn post draft generated by the Content Strategist. "
        "The entire text of the final draft is the input for the tool."
    ),
    expected_output='A confirmation message that the email was successfully sent.',
    context=[summarize_task], # The final draft is the context for this one
    agent=deliverer
)

# 4. Form and Kickoff the Crew
ai_news_crew = Crew(
    agents=[researcher, strategist, deliverer],
    tasks=[research_task, summarize_task, email_task],
    process=Process.sequential, # Tasks run one after the other
    verbose=True # Verbose logging shows the agents' reasoning
)

print("--- Starting AI News Digest Crew ---")
result = ai_news_crew.kickoff()
print("\n\n######################################")
print("Crew Final Output:")
print("######################################")
print(result)